### ISSUE TITLE
Ingest Crito alignment from Ugarit

### ISSUE THREAD

**Issue by jacobwegner** [scaife-viewer/beyond-translation-site#65]
@farnoosh-shamsian will provide the link to Ugrait (or the CSV output).  As long as we are using the same Greek version from scaife.perseus.org ([urn:cts:greekLit:tlg0059.tlg003.perseus-grc2](https://github.com/PerseusDL/canonical-greekLit/blob/a0985e4a3ad01471b7cb4093798af3c759293807/data/tlg0059/tlg003/tlg0059.tlg003.perseus-grc2.xml)), we should be able to ingest things.

**Comment by jacobwegner** [comment]
@farnoosh-shamsian: I spent some time on this today.

Should have something to show soon and can follow up with Tariq about the longer term needs for an export.

**Comment by jacobwegner** [comment]
I'll start building out some metadata to go with this:

```yaml
ugarit_url: "https://ugarit.ialigner.com/userProfile.php?userid=40&tgid=8612"
label: "LREC Crito"
annotator: "Farnoosh Shamsian"
scaife_reader_url: "https://scaife.perseus.org/reader/urn:cts:greekLit:tlg0059.tlg003.perseus-grc2:43-48/?highlight=@ΣΩ[1]-ἐναντίων[1]"
versions:
  - "greek"
  - "eng"
```
